name: 'go-semantic-release'
description: 'fully automated package/module/image publishing'
branding:
  icon: 'package'
  color: 'blue'
inputs:
  github-token:
    description: 'github token'
    required: true
  pre-release-post-dry-cmd:
    description: 'command to run between dry release and actual release'
    required: false
outputs:
  version:
    description: 'the version of the created release'
  version_major:
    description: 'the major version of the created release'
  version_minor:
    description: 'the minor version of the created release'
  version_patch:
    description: 'the patch version of the created release'
  version_prerelease:
    description: 'the prerelease version of the created release'
runs:
  using: 'node20'
  main: 'dist/index.js'
